version: '3.8'

services:
  api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api_final
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - SERVER_URL=${SERVER_URL}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - DATABASE_CONNECTION_CLIENT_NAME=${DATABASE_CONNECTION_CLIENT_NAME}
      - DATABASE_SAVE_DATA_INSTANCE=${DATABASE_SAVE_DATA_INSTANCE}
      - DATABASE_SAVE_DATA_NEW_MESSAGE=${DATABASE_SAVE_DATA_NEW_MESSAGE}
      - DATABASE_SAVE_MESSAGE_UPDATE=${DATABASE_SAVE_MESSAGE_UPDATE}
      - DATABASE_SAVE_DATA_CONTACTS=${DATABASE_SAVE_DATA_CONTACTS}
      - DATABASE_SAVE_DATA_CHATS=${DATABASE_SAVE_DATA_CHATS}
      - DATABASE_SAVE_DATA_LABELS=${DATABASE_SAVE_DATA_LABELS}
      - DATABASE_SAVE_DATA_HISTORIC=${DATABASE_SAVE_DATA_HISTORIC}
      - DEL_INSTANCE=${DEL_INSTANCE}
      - CACHE_REDIS_ENABLED=${CACHE_REDIS_ENABLED}
      - CACHE_REDIS_URI=${CACHE_REDIS_URI}
      - CACHE_REDIS_PREFIX_KEY=${CACHE_REDIS_PREFIX_KEY}
      - CACHE_REDIS_SAVE_INSTANCES=${CACHE_REDIS_SAVE_INSTANCES}
      - CACHE_LOCAL_ENABLED=${CACHE_LOCAL_ENABLED}
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES}
      - WEBHOOK_EVENTS_QRCODE_UPDATED=${WEBHOOK_EVENTS_QRCODE_UPDATED}
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=${WEBHOOK_EVENTS_CONNECTION_UPDATE}
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=${WEBHOOK_EVENTS_MESSAGES_UPSERT}
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME}
      - QRCODE_LIMIT=${QRCODE_LIMIT}
      - LANGUAGE=${LANGUAGE}
      - TYPEBOT_ENABLED=${TYPEBOT_ENABLED}
      - CHATWOOT_ENABLED=${CHATWOOT_ENABLED}
      - OPENAI_ENABLED=${OPENAI_ENABLED}
      - RABBITMQ_ENABLED=${RABBITMQ_ENABLED}
      - SQS_ENABLED=${SQS_ENABLED}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution

  redis:
    image: redis:latest
    container_name: evolution_redis_final
    command: redis-server --port 6379 --appendonly yes
    restart: always
    volumes:
      - evolution_redis:/data
    networks:
      - evolution

  postgres:
    image: postgres:16-alpine
    container_name: evolution_postgres_final
    restart: always
    command:
      - postgres
      - '-c'
      - max_connections=1000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution:
    driver: bridge
